### ISSUE TITLE
Update angular version to 13, publish with ivy

### ISSUE THREAD

**Issue by bufke** [Tinkoff/micro-sentry#17]
# 🚀 Feature request

### Is your feature request related to a problem?

Newer versions of Angular replace View Engine with Ivy. For compatibility, ngcc is run after installing an older published library. Updating would speed up installation and remove these lines from installation.

```
- @micro-sentry/core [es2015/esm2015] (https://github.com/TinkoffCreditSystems/micro-sentry)
- @micro-sentry/browser [es2015/esm2015] (https://github.com/TinkoffCreditSystems/micro-sentry)
- @micro-sentry/angular [es2015/esm2015] (https://github.com/TinkoffCreditSystems/micro-sentry)
```

### Describe the solution you'd like

Update @micro-sentry/angular to version 13 and publish an update to npm.

### Additional context

If interested, I'd be happy to submit a pull request for this. I plan to use this library on [GlitchTip](https://gitlab.com/glitchtip-frontend/), an open source alternative to sentry.

I also need to set config values dynamically. I can work around this since it's really only a TypeScript level issue. However I'm happy to help review and work on pull requests if you'd like around the subject.

**Comment by IKatsuba** [comment]
@bufke thank you for issue! I would be happy to review your PR)

**Comment by IKatsuba** [comment]
@bufke hi!
I have upgraded the Angular package step by step from 10 to 14. You can use it now, just pick up your version

| Micro-sentry version | Angular version |
| -------------------- | --------------- |
| `>= 6`               | `>= 14`         |
| `>= 5`               | `>= 13`         |
| `>= 4`               | `>= 12`         |
| `>= 3`               | `>= 11`         |
| `>= 2`               | `>= 10`         |
