### ISSUE TITLE
[BUG] @ng-web-apis module can't be resolved in CI pippeline testing

### ISSUE THREAD

**Issue by jamesrkiger** [Tinkoff/micro-sentry#26]
# 🐞 Bug report

### Description

Micro-Sentry versions starting with 3.0.0 break ng test in a CI pipeline with the following error:
./node_modules/@micro-sentry/angular/fesm2020/micro-sentry-angular.mjs:9:0-45 - Error: Module not found: Error: Can't resolve '@ng-web-apis/common' in '/builds/glitchtip/glitchtip-frontend/node_modules/@micro-sentry/angular/fesm2020' .

### Reproduction

I have only been able to reproduce this in the CI pipeline. It does not happen locally and only appears to impact testing.

### Expected behavior

Tests shouldn't break and the @ng-web-apis peer dependency should be handled by micro-sentry.

### Versions

@micro-sentry V.3.0.0 and above

If needed:

Angular 14

### Additional context

 As an experiment, I was able to avoid this error by adding @ng-web-apis/common as a dependency on my own project. But I don't think that should be necessary. 
 
 I set up a repository for testing. You can see the failed pipeline here:
 https://gitlab.com/james.kiger/micro-sentry-test/-/jobs/2576177389

**Comment by bufke** [comment]
@jamesrkiger you seem to be using a very old docker image called "gitlab.com/dasch8/angular-ci" I suspect it likely has a very old node/npm version. Could you try reproducing with the latest node 16.x and npm? I would suggest pulling the "node" docker image if docker is preferred.
