### ISSUE TITLE
[BUG] Exclude tslib from bundle?

### ISSUE THREAD

**Issue by danielcompton** [Tinkoff/micro-sentry#34]
# 🐞 Bug report

### Description

https://bundlephobia.com/package/@micro-sentry/browser@6.0.0 shows that a big part of the package size comes from tslib. Is that necessary in the browser bundle? 

### Reproduction

Go to https://bundlephobia.com/package/@micro-sentry/browser@6.0.0

### Expected behavior

https://bundlephobia.com/package/@micro-sentry/browser@6.0.0 doesn't show tslib (if possible?)

### Versions

- Package @micro-sentry/browser@6.0.0

### Additional context

It looks like tslib is only being used for `__assign`. Would it be possible to use a different polyfill or perhaps avoid Object.assign and add the keys directly?

**Comment by IKatsuba** [comment]
@danielcompton thank you!
